// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/v1/plugin.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KindCategory int32

const (
	KindCategory_KIND_DATASOURCE KindCategory = 0 // Treated as a DataSource variant
	KindCategory_KIND_COMPONENT  KindCategory = 1 // Treated as a visual component (future)
	KindCategory_KIND_CONFIG     KindCategory = 2 // Treated as configuration (future)
	KindCategory_KIND_ARTIFACT   KindCategory = 3 // Treated as an artifact type (future)
)

// Enum value maps for KindCategory.
var (
	KindCategory_name = map[int32]string{
		0: "KIND_DATASOURCE",
		1: "KIND_COMPONENT",
		2: "KIND_CONFIG",
		3: "KIND_ARTIFACT",
	}
	KindCategory_value = map[string]int32{
		"KIND_DATASOURCE": 0,
		"KIND_COMPONENT":  1,
		"KIND_CONFIG":     2,
		"KIND_ARTIFACT":   3,
	}
)

func (x KindCategory) Enum() *KindCategory {
	p := new(KindCategory)
	*p = x
	return p
}

func (x KindCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KindCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_plugin_proto_enumTypes[0].Descriptor()
}

func (KindCategory) Type() protoreflect.EnumType {
	return &file_proto_v1_plugin_proto_enumTypes[0]
}

func (x KindCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KindCategory.Descriptor instead.
func (KindCategory) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{0}
}

type Severity int32

const (
	Severity_WARNING Severity = 0
	Severity_ERROR   Severity = 1
	Severity_INFO    Severity = 2
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "WARNING",
		1: "ERROR",
		2: "INFO",
	}
	Severity_value = map[string]int32{
		"WARNING": 0,
		"ERROR":   1,
		"INFO":    2,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_plugin_proto_enumTypes[1].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_proto_v1_plugin_proto_enumTypes[1]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{1}
}

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // From bino.toml [plugins.<name>.config]
	ProjectRoot   string                 `protobuf:"bytes,2,opt,name=project_root,json=projectRoot,proto3" json:"project_root,omitempty"`
	BinoVersion   string                 `protobuf:"bytes,3,opt,name=bino_version,json=binoVersion,proto3" json:"bino_version,omitempty"`
	HostServiceId uint32                 `protobuf:"varint,4,opt,name=host_service_id,json=hostServiceId,proto3" json:"host_service_id,omitempty"` // Broker ID for BinoHost service (0 = not available)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_proto_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *InitRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *InitRequest) GetProjectRoot() string {
	if x != nil {
		return x.ProjectRoot
	}
	return ""
}

func (x *InitRequest) GetBinoVersion() string {
	if x != nil {
		return x.BinoVersion
	}
	return ""
}

func (x *InitRequest) GetHostServiceId() uint32 {
	if x != nil {
		return x.HostServiceId
	}
	return 0
}

type PluginManifest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`       // e.g., "salesforce"
	Version     string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // semver
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Capabilities — what this plugin provides
	Kinds            []*KindRegistration  `protobuf:"bytes,10,rep,name=kinds,proto3" json:"kinds,omitempty"`
	DuckdbExtensions []string             `protobuf:"bytes,11,rep,name=duckdb_extensions,json=duckdbExtensions,proto3" json:"duckdb_extensions,omitempty"` // e.g., ["httpfs", "spatial"]
	ProvidesLinter   bool                 `protobuf:"varint,12,opt,name=provides_linter,json=providesLinter,proto3" json:"provides_linter,omitempty"`
	ProvidesAssets   bool                 `protobuf:"varint,13,opt,name=provides_assets,json=providesAssets,proto3" json:"provides_assets,omitempty"`
	Commands         []*CommandDescriptor `protobuf:"bytes,14,rep,name=commands,proto3" json:"commands,omitempty"`
	Hooks            []string             `protobuf:"bytes,15,rep,name=hooks,proto3" json:"hooks,omitempty"` // checkpoints this plugin wants to receive
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PluginManifest) Reset() {
	*x = PluginManifest{}
	mi := &file_proto_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginManifest) ProtoMessage() {}

func (x *PluginManifest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginManifest.ProtoReflect.Descriptor instead.
func (*PluginManifest) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *PluginManifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginManifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginManifest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginManifest) GetKinds() []*KindRegistration {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *PluginManifest) GetDuckdbExtensions() []string {
	if x != nil {
		return x.DuckdbExtensions
	}
	return nil
}

func (x *PluginManifest) GetProvidesLinter() bool {
	if x != nil {
		return x.ProvidesLinter
	}
	return false
}

func (x *PluginManifest) GetProvidesAssets() bool {
	if x != nil {
		return x.ProvidesAssets
	}
	return false
}

func (x *PluginManifest) GetCommands() []*CommandDescriptor {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *PluginManifest) GetHooks() []string {
	if x != nil {
		return x.Hooks
	}
	return nil
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_proto_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{2}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_proto_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{3}
}

type KindRegistration struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	KindName string                 `protobuf:"bytes,1,opt,name=kind_name,json=kindName,proto3" json:"kind_name,omitempty"`                   // e.g., "SalesforceDataSource"
	Category KindCategory           `protobuf:"varint,2,opt,name=category,proto3,enum=bino.plugin.v1.KindCategory" json:"category,omitempty"` // How bino treats this kind internally
	// datasource_type is set when category = KIND_DATASOURCE.
	// This is the value of spec.type for routing to CollectDataSource.
	DatasourceType string `protobuf:"bytes,3,opt,name=datasource_type,json=datasourceType,proto3" json:"datasource_type,omitempty"` // e.g., "salesforce_soql"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KindRegistration) Reset() {
	*x = KindRegistration{}
	mi := &file_proto_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KindRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KindRegistration) ProtoMessage() {}

func (x *KindRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KindRegistration.ProtoReflect.Descriptor instead.
func (*KindRegistration) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *KindRegistration) GetKindName() string {
	if x != nil {
		return x.KindName
	}
	return ""
}

func (x *KindRegistration) GetCategory() KindCategory {
	if x != nil {
		return x.Category
	}
	return KindCategory_KIND_DATASOURCE
}

func (x *KindRegistration) GetDatasourceType() string {
	if x != nil {
		return x.DatasourceType
	}
	return ""
}

type GetSchemasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemasRequest) Reset() {
	*x = GetSchemasRequest{}
	mi := &file_proto_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemasRequest) ProtoMessage() {}

func (x *GetSchemasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemasRequest.ProtoReflect.Descriptor instead.
func (*GetSchemasRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{5}
}

type GetSchemasResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of kind_name -> JSON Schema (as JSON bytes)
	Schemas       map[string][]byte `protobuf:"bytes,1,rep,name=schemas,proto3" json:"schemas,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemasResponse) Reset() {
	*x = GetSchemasResponse{}
	mi := &file_proto_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemasResponse) ProtoMessage() {}

func (x *GetSchemasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemasResponse.ProtoReflect.Descriptor instead.
func (*GetSchemasResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *GetSchemasResponse) GetSchemas() map[string][]byte {
	if x != nil {
		return x.Schemas
	}
	return nil
}

type CollectDataSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                                         // metadata.name
	RawSpec       []byte                 `protobuf:"bytes,2,opt,name=raw_spec,json=rawSpec,proto3" json:"raw_spec,omitempty"`                                                    // JSON of the spec section
	Env           map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // resolved environment variables
	ProjectRoot   string                 `protobuf:"bytes,4,opt,name=project_root,json=projectRoot,proto3" json:"project_root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectDataSourceRequest) Reset() {
	*x = CollectDataSourceRequest{}
	mi := &file_proto_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectDataSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectDataSourceRequest) ProtoMessage() {}

func (x *CollectDataSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectDataSourceRequest.ProtoReflect.Descriptor instead.
func (*CollectDataSourceRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *CollectDataSourceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CollectDataSourceRequest) GetRawSpec() []byte {
	if x != nil {
		return x.RawSpec
	}
	return nil
}

func (x *CollectDataSourceRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *CollectDataSourceRequest) GetProjectRoot() string {
	if x != nil {
		return x.ProjectRoot
	}
	return ""
}

type CollectDataSourceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON array of objects — each object becomes a row in the DuckDB view
	JsonRows []byte `protobuf:"bytes,1,opt,name=json_rows,json=jsonRows,proto3" json:"json_rows,omitempty"`
	// Column type hints (optional). If omitted, DuckDB infers types.
	ColumnTypes map[string]string `protobuf:"bytes,2,rep,name=column_types,json=columnTypes,proto3" json:"column_types,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Whether this source is ephemeral (always re-fetched)
	Ephemeral bool `protobuf:"varint,3,opt,name=ephemeral,proto3" json:"ephemeral,omitempty"`
	// Diagnostics (non-fatal warnings)
	Diagnostics []*Diagnostic `protobuf:"bytes,4,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	// DuckDB SQL expression to register as a view instead of json_rows.
	// When set, json_rows is ignored. Example: "read_parquet('s3://...')"
	DuckdbExpression string `protobuf:"bytes,5,opt,name=duckdb_expression,json=duckdbExpression,proto3" json:"duckdb_expression,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CollectDataSourceResponse) Reset() {
	*x = CollectDataSourceResponse{}
	mi := &file_proto_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectDataSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectDataSourceResponse) ProtoMessage() {}

func (x *CollectDataSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectDataSourceResponse.ProtoReflect.Descriptor instead.
func (*CollectDataSourceResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *CollectDataSourceResponse) GetJsonRows() []byte {
	if x != nil {
		return x.JsonRows
	}
	return nil
}

func (x *CollectDataSourceResponse) GetColumnTypes() map[string]string {
	if x != nil {
		return x.ColumnTypes
	}
	return nil
}

func (x *CollectDataSourceResponse) GetEphemeral() bool {
	if x != nil {
		return x.Ephemeral
	}
	return false
}

func (x *CollectDataSourceResponse) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

func (x *CollectDataSourceResponse) GetDuckdbExpression() string {
	if x != nil {
		return x.DuckdbExpression
	}
	return ""
}

type LintRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Documents []*LintDocument        `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	// Optional: pre-computed dataset results for data-aware linting.
	Datasets []*DatasetPayload `protobuf:"bytes,2,rep,name=datasets,proto3" json:"datasets,omitempty"`
	// Whether datasets field is populated.
	DatasetsAvailable bool `protobuf:"varint,3,opt,name=datasets_available,json=datasetsAvailable,proto3" json:"datasets_available,omitempty"`
	// Optional: rendered HTML for output validation.
	RenderedHtml  []byte `protobuf:"bytes,4,opt,name=rendered_html,json=renderedHtml,proto3" json:"rendered_html,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LintRequest) Reset() {
	*x = LintRequest{}
	mi := &file_proto_v1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LintRequest) ProtoMessage() {}

func (x *LintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LintRequest.ProtoReflect.Descriptor instead.
func (*LintRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *LintRequest) GetDocuments() []*LintDocument {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *LintRequest) GetDatasets() []*DatasetPayload {
	if x != nil {
		return x.Datasets
	}
	return nil
}

func (x *LintRequest) GetDatasetsAvailable() bool {
	if x != nil {
		return x.DatasetsAvailable
	}
	return false
}

func (x *LintRequest) GetRenderedHtml() []byte {
	if x != nil {
		return x.RenderedHtml
	}
	return nil
}

type LintDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          string                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Position      int32                  `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Raw           []byte                 `protobuf:"bytes,5,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LintDocument) Reset() {
	*x = LintDocument{}
	mi := &file_proto_v1_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LintDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LintDocument) ProtoMessage() {}

func (x *LintDocument) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LintDocument.ProtoReflect.Descriptor instead.
func (*LintDocument) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *LintDocument) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *LintDocument) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *LintDocument) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *LintDocument) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LintDocument) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type LintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Findings      []*LintFinding         `protobuf:"bytes,1,rep,name=findings,proto3" json:"findings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LintResponse) Reset() {
	*x = LintResponse{}
	mi := &file_proto_v1_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LintResponse) ProtoMessage() {}

func (x *LintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LintResponse.ProtoReflect.Descriptor instead.
func (*LintResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *LintResponse) GetFindings() []*LintFinding {
	if x != nil {
		return x.Findings
	}
	return nil
}

type LintFinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"` // Prefixed with plugin name: "salesforce/field-access"
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	File          string                 `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
	DocIdx        int32                  `protobuf:"varint,4,opt,name=doc_idx,json=docIdx,proto3" json:"doc_idx,omitempty"`
	Path          string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	Line          int32                  `protobuf:"varint,6,opt,name=line,proto3" json:"line,omitempty"`
	Column        int32                  `protobuf:"varint,7,opt,name=column,proto3" json:"column,omitempty"`
	Severity      Severity               `protobuf:"varint,8,opt,name=severity,proto3,enum=bino.plugin.v1.Severity" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LintFinding) Reset() {
	*x = LintFinding{}
	mi := &file_proto_v1_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LintFinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LintFinding) ProtoMessage() {}

func (x *LintFinding) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LintFinding.ProtoReflect.Descriptor instead.
func (*LintFinding) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *LintFinding) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *LintFinding) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LintFinding) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *LintFinding) GetDocIdx() int32 {
	if x != nil {
		return x.DocIdx
	}
	return 0
}

func (x *LintFinding) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *LintFinding) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *LintFinding) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *LintFinding) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_WARNING
}

type GetAssetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RenderMode    string                 `protobuf:"bytes,1,opt,name=render_mode,json=renderMode,proto3" json:"render_mode,omitempty"` // "build" or "preview"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetsRequest) Reset() {
	*x = GetAssetsRequest{}
	mi := &file_proto_v1_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetsRequest) ProtoMessage() {}

func (x *GetAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetsRequest.ProtoReflect.Descriptor instead.
func (*GetAssetsRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *GetAssetsRequest) GetRenderMode() string {
	if x != nil {
		return x.RenderMode
	}
	return ""
}

type GetAssetsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JS modules to inject into <head>
	Scripts []*AssetFile `protobuf:"bytes,1,rep,name=scripts,proto3" json:"scripts,omitempty"`
	// CSS files to inject into <head>
	Styles        []*AssetFile `protobuf:"bytes,2,rep,name=styles,proto3" json:"styles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetsResponse) Reset() {
	*x = GetAssetsResponse{}
	mi := &file_proto_v1_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetsResponse) ProtoMessage() {}

func (x *GetAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetsResponse.ProtoReflect.Descriptor instead.
func (*GetAssetsResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *GetAssetsResponse) GetScripts() []*AssetFile {
	if x != nil {
		return x.Scripts
	}
	return nil
}

func (x *GetAssetsResponse) GetStyles() []*AssetFile {
	if x != nil {
		return x.Styles
	}
	return nil
}

type AssetFile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique URL path for serving (e.g., "/plugins/salesforce/chart.js")
	UrlPath string `protobuf:"bytes,1,opt,name=url_path,json=urlPath,proto3" json:"url_path,omitempty"`
	// The file content (inline). For large assets, consider file_path instead.
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Alternative: absolute path to a file on disk the host should serve.
	FilePath string `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	// MIME type (auto-detected from extension if empty)
	MediaType string `protobuf:"bytes,4,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	// Whether this is an ES module script (type="module")
	IsModule      bool `protobuf:"varint,5,opt,name=is_module,json=isModule,proto3" json:"is_module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetFile) Reset() {
	*x = AssetFile{}
	mi := &file_proto_v1_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetFile) ProtoMessage() {}

func (x *AssetFile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetFile.ProtoReflect.Descriptor instead.
func (*AssetFile) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *AssetFile) GetUrlPath() string {
	if x != nil {
		return x.UrlPath
	}
	return ""
}

func (x *AssetFile) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *AssetFile) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *AssetFile) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *AssetFile) GetIsModule() bool {
	if x != nil {
		return x.IsModule
	}
	return false
}

type CommandDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`   // Subcommand name: "bino salesforce:auth"
	Short         string                 `protobuf:"bytes,2,opt,name=short,proto3" json:"short,omitempty"` // One-line description for help
	Long          string                 `protobuf:"bytes,3,opt,name=long,proto3" json:"long,omitempty"`   // Detailed help text
	Usage         string                 `protobuf:"bytes,4,opt,name=usage,proto3" json:"usage,omitempty"` // Usage pattern
	Flags         []*FlagDescriptor      `protobuf:"bytes,5,rep,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandDescriptor) Reset() {
	*x = CommandDescriptor{}
	mi := &file_proto_v1_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandDescriptor) ProtoMessage() {}

func (x *CommandDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandDescriptor.ProtoReflect.Descriptor instead.
func (*CommandDescriptor) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *CommandDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CommandDescriptor) GetShort() string {
	if x != nil {
		return x.Short
	}
	return ""
}

func (x *CommandDescriptor) GetLong() string {
	if x != nil {
		return x.Long
	}
	return ""
}

func (x *CommandDescriptor) GetUsage() string {
	if x != nil {
		return x.Usage
	}
	return ""
}

func (x *CommandDescriptor) GetFlags() []*FlagDescriptor {
	if x != nil {
		return x.Flags
	}
	return nil
}

type FlagDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Shorthand     string                 `protobuf:"bytes,2,opt,name=shorthand,proto3" json:"shorthand,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DefaultValue  string                 `protobuf:"bytes,4,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"` // "string", "bool", "int"
	Required      bool                   `protobuf:"varint,6,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlagDescriptor) Reset() {
	*x = FlagDescriptor{}
	mi := &file_proto_v1_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagDescriptor) ProtoMessage() {}

func (x *FlagDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagDescriptor.ProtoReflect.Descriptor instead.
func (*FlagDescriptor) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *FlagDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FlagDescriptor) GetShorthand() string {
	if x != nil {
		return x.Shorthand
	}
	return ""
}

func (x *FlagDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FlagDescriptor) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *FlagDescriptor) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FlagDescriptor) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

type ExecCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Flags         map[string]string      `protobuf:"bytes,3,rep,name=flags,proto3" json:"flags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Workdir       string                 `protobuf:"bytes,4,opt,name=workdir,proto3" json:"workdir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecCommandRequest) Reset() {
	*x = ExecCommandRequest{}
	mi := &file_proto_v1_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecCommandRequest) ProtoMessage() {}

func (x *ExecCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecCommandRequest.ProtoReflect.Descriptor instead.
func (*ExecCommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *ExecCommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecCommandRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecCommandRequest) GetFlags() map[string]string {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *ExecCommandRequest) GetWorkdir() string {
	if x != nil {
		return x.Workdir
	}
	return ""
}

type ExecCommandOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        []byte                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        []byte                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"` // Only set in the final message
	IsFinal       bool                   `protobuf:"varint,4,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecCommandOutput) Reset() {
	*x = ExecCommandOutput{}
	mi := &file_proto_v1_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecCommandOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecCommandOutput) ProtoMessage() {}

func (x *ExecCommandOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecCommandOutput.ProtoReflect.Descriptor instead.
func (*ExecCommandOutput) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *ExecCommandOutput) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *ExecCommandOutput) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *ExecCommandOutput) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecCommandOutput) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

type HookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checkpoint    string                 `protobuf:"bytes,1,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"` // e.g., "post-load", "pre-render-html"
	Payload       *HookPayload           `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookRequest) Reset() {
	*x = HookRequest{}
	mi := &file_proto_v1_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookRequest) ProtoMessage() {}

func (x *HookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookRequest.ProtoReflect.Descriptor instead.
func (*HookRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *HookRequest) GetCheckpoint() string {
	if x != nil {
		return x.Checkpoint
	}
	return ""
}

func (x *HookRequest) GetPayload() *HookPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type HookPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Depending on checkpoint, one of these is populated:
	Documents     []*DocumentPayload `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`                                                                          // post-load, pre-render
	Html          []byte             `protobuf:"bytes,2,opt,name=html,proto3" json:"html,omitempty"`                                                                                    // post-render-html
	PdfPath       string             `protobuf:"bytes,3,opt,name=pdf_path,json=pdfPath,proto3" json:"pdf_path,omitempty"`                                                               // post-render-pdf
	Datasets      []*DatasetPayload  `protobuf:"bytes,4,rep,name=datasets,proto3" json:"datasets,omitempty"`                                                                            // post-dataset-execute
	Metadata      map[string]string  `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Always available
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookPayload) Reset() {
	*x = HookPayload{}
	mi := &file_proto_v1_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookPayload) ProtoMessage() {}

func (x *HookPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookPayload.ProtoReflect.Descriptor instead.
func (*HookPayload) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *HookPayload) GetDocuments() []*DocumentPayload {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *HookPayload) GetHtml() []byte {
	if x != nil {
		return x.Html
	}
	return nil
}

func (x *HookPayload) GetPdfPath() string {
	if x != nil {
		return x.PdfPath
	}
	return ""
}

func (x *HookPayload) GetDatasets() []*DatasetPayload {
	if x != nil {
		return x.Datasets
	}
	return nil
}

func (x *HookPayload) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DocumentPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          string                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Position      int32                  `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Raw           []byte                 `protobuf:"bytes,5,opt,name=raw,proto3" json:"raw,omitempty"` // JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentPayload) Reset() {
	*x = DocumentPayload{}
	mi := &file_proto_v1_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentPayload) ProtoMessage() {}

func (x *DocumentPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentPayload.ProtoReflect.Descriptor instead.
func (*DocumentPayload) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *DocumentPayload) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *DocumentPayload) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *DocumentPayload) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DocumentPayload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DocumentPayload) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type DatasetPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	JsonRows      []byte                 `protobuf:"bytes,2,opt,name=json_rows,json=jsonRows,proto3" json:"json_rows,omitempty"` // JSON array
	Columns       []string               `protobuf:"bytes,3,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatasetPayload) Reset() {
	*x = DatasetPayload{}
	mi := &file_proto_v1_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatasetPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatasetPayload) ProtoMessage() {}

func (x *DatasetPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatasetPayload.ProtoReflect.Descriptor instead.
func (*DatasetPayload) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{23}
}

func (x *DatasetPayload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DatasetPayload) GetJsonRows() []byte {
	if x != nil {
		return x.JsonRows
	}
	return nil
}

func (x *DatasetPayload) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

type HookResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If modified = true, the host uses the returned payload
	// instead of the original. If false, the original is kept.
	Modified bool         `protobuf:"varint,1,opt,name=modified,proto3" json:"modified,omitempty"`
	Payload  *HookPayload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// Diagnostics from hook processing
	Diagnostics []*Diagnostic `protobuf:"bytes,3,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	// Structured lint findings from hook processing.
	Findings      []*LintFinding `protobuf:"bytes,4,rep,name=findings,proto3" json:"findings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookResponse) Reset() {
	*x = HookResponse{}
	mi := &file_proto_v1_plugin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookResponse) ProtoMessage() {}

func (x *HookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookResponse.ProtoReflect.Descriptor instead.
func (*HookResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{24}
}

func (x *HookResponse) GetModified() bool {
	if x != nil {
		return x.Modified
	}
	return false
}

func (x *HookResponse) GetPayload() *HookPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HookResponse) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

func (x *HookResponse) GetFindings() []*LintFinding {
	if x != nil {
		return x.Findings
	}
	return nil
}

type Diagnostic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"` // plugin name
	Stage         string                 `protobuf:"bytes,2,opt,name=stage,proto3" json:"stage,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Severity      Severity               `protobuf:"varint,4,opt,name=severity,proto3,enum=bino.plugin.v1.Severity" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diagnostic) Reset() {
	*x = Diagnostic{}
	mi := &file_proto_v1_plugin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostic) ProtoMessage() {}

func (x *Diagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostic.ProtoReflect.Descriptor instead.
func (*Diagnostic) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{25}
}

func (x *Diagnostic) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Diagnostic) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *Diagnostic) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Diagnostic) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_WARNING
}

type ListCommandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommandsRequest) Reset() {
	*x = ListCommandsRequest{}
	mi := &file_proto_v1_plugin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommandsRequest) ProtoMessage() {}

func (x *ListCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommandsRequest.ProtoReflect.Descriptor instead.
func (*ListCommandsRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{26}
}

type ListCommandsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*CommandDescriptor   `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommandsResponse) Reset() {
	*x = ListCommandsResponse{}
	mi := &file_proto_v1_plugin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommandsResponse) ProtoMessage() {}

func (x *ListCommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommandsResponse.ProtoReflect.Descriptor instead.
func (*ListCommandsResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{27}
}

func (x *ListCommandsResponse) GetCommands() []*CommandDescriptor {
	if x != nil {
		return x.Commands
	}
	return nil
}

type RenderComponentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`                               // e.g., "ExampleChart"
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                               // metadata.name of the document
	Spec          []byte                 `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`                               // JSON of the effective spec (after ref resolution + overrides)
	RenderMode    string                 `protobuf:"bytes,4,opt,name=render_mode,json=renderMode,proto3" json:"render_mode,omitempty"` // "build" or "preview"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderComponentRequest) Reset() {
	*x = RenderComponentRequest{}
	mi := &file_proto_v1_plugin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderComponentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderComponentRequest) ProtoMessage() {}

func (x *RenderComponentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderComponentRequest.ProtoReflect.Descriptor instead.
func (*RenderComponentRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{28}
}

func (x *RenderComponentRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *RenderComponentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RenderComponentRequest) GetSpec() []byte {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *RenderComponentRequest) GetRenderMode() string {
	if x != nil {
		return x.RenderMode
	}
	return ""
}

type RenderComponentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTML fragment to insert into the layout slot.
	// Must be a single root element (e.g., <bn-example-chart ...>...</bn-example-chart>)
	Html string `protobuf:"bytes,1,opt,name=html,proto3" json:"html,omitempty"`
	// Diagnostics from rendering.
	Diagnostics   []*Diagnostic `protobuf:"bytes,2,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderComponentResponse) Reset() {
	*x = RenderComponentResponse{}
	mi := &file_proto_v1_plugin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderComponentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderComponentResponse) ProtoMessage() {}

func (x *RenderComponentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderComponentResponse.ProtoReflect.Descriptor instead.
func (*RenderComponentResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{29}
}

func (x *RenderComponentResponse) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

func (x *RenderComponentResponse) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_proto_v1_plugin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{30}
}

func (x *QueryRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonRows      []byte                 `protobuf:"bytes,1,opt,name=json_rows,json=jsonRows,proto3" json:"json_rows,omitempty"` // JSON array of row objects
	Columns       []string               `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	Diagnostics   []*Diagnostic          `protobuf:"bytes,3,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_proto_v1_plugin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{31}
}

func (x *QueryResponse) GetJsonRows() []byte {
	if x != nil {
		return x.JsonRows
	}
	return nil
}

func (x *QueryResponse) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *QueryResponse) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type GetDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"` // optional: filter by kind
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // required: document name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_proto_v1_plugin_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{32}
}

func (x *GetDocumentRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GetDocumentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *DocumentPayload       `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentResponse) Reset() {
	*x = GetDocumentResponse{}
	mi := &file_proto_v1_plugin_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentResponse) ProtoMessage() {}

func (x *GetDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentResponse.ProtoReflect.Descriptor instead.
func (*GetDocumentResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{33}
}

func (x *GetDocumentResponse) GetDocument() *DocumentPayload {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *GetDocumentResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type GetDatasetResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatasetResultRequest) Reset() {
	*x = GetDatasetResultRequest{}
	mi := &file_proto_v1_plugin_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatasetResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatasetResultRequest) ProtoMessage() {}

func (x *GetDatasetResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatasetResultRequest.ProtoReflect.Descriptor instead.
func (*GetDatasetResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{34}
}

func (x *GetDatasetResultRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetDatasetResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dataset       *DatasetPayload        `protobuf:"bytes,1,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatasetResultResponse) Reset() {
	*x = GetDatasetResultResponse{}
	mi := &file_proto_v1_plugin_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatasetResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatasetResultResponse) ProtoMessage() {}

func (x *GetDatasetResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatasetResultResponse.ProtoReflect.Descriptor instead.
func (*GetDatasetResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{35}
}

func (x *GetDatasetResultResponse) GetDataset() *DatasetPayload {
	if x != nil {
		return x.Dataset
	}
	return nil
}

func (x *GetDatasetResultResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type ListDocumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KindFilter    string                 `protobuf:"bytes,1,opt,name=kind_filter,json=kindFilter,proto3" json:"kind_filter,omitempty"` // optional: filter by kind (empty = all)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsRequest) Reset() {
	*x = ListDocumentsRequest{}
	mi := &file_proto_v1_plugin_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsRequest) ProtoMessage() {}

func (x *ListDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsRequest.ProtoReflect.Descriptor instead.
func (*ListDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{36}
}

func (x *ListDocumentsRequest) GetKindFilter() string {
	if x != nil {
		return x.KindFilter
	}
	return ""
}

type ListDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*DocumentPayload     `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsResponse) Reset() {
	*x = ListDocumentsResponse{}
	mi := &file_proto_v1_plugin_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsResponse) ProtoMessage() {}

func (x *ListDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_plugin_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsResponse.ProtoReflect.Descriptor instead.
func (*ListDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_plugin_proto_rawDescGZIP(), []int{37}
}

func (x *ListDocumentsResponse) GetDocuments() []*DocumentPayload {
	if x != nil {
		return x.Documents
	}
	return nil
}

var File_proto_v1_plugin_proto protoreflect.FileDescriptor

const file_proto_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x15proto/v1/plugin.proto\x12\x0ebino.plugin.v1\"\xf7\x01\n" +
	"\vInitRequest\x12?\n" +
	"\x06config\x18\x01 \x03(\v2'.bino.plugin.v1.InitRequest.ConfigEntryR\x06config\x12!\n" +
	"\fproject_root\x18\x02 \x01(\tR\vprojectRoot\x12!\n" +
	"\fbino_version\x18\x03 \x01(\tR\vbinoVersion\x12&\n" +
	"\x0fhost_service_id\x18\x04 \x01(\rR\rhostServiceId\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xec\x02\n" +
	"\x0ePluginManifest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x126\n" +
	"\x05kinds\x18\n" +
	" \x03(\v2 .bino.plugin.v1.KindRegistrationR\x05kinds\x12+\n" +
	"\x11duckdb_extensions\x18\v \x03(\tR\x10duckdbExtensions\x12'\n" +
	"\x0fprovides_linter\x18\f \x01(\bR\x0eprovidesLinter\x12'\n" +
	"\x0fprovides_assets\x18\r \x01(\bR\x0eprovidesAssets\x12=\n" +
	"\bcommands\x18\x0e \x03(\v2!.bino.plugin.v1.CommandDescriptorR\bcommands\x12\x14\n" +
	"\x05hooks\x18\x0f \x03(\tR\x05hooks\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse\"\x92\x01\n" +
	"\x10KindRegistration\x12\x1b\n" +
	"\tkind_name\x18\x01 \x01(\tR\bkindName\x128\n" +
	"\bcategory\x18\x02 \x01(\x0e2\x1c.bino.plugin.v1.KindCategoryR\bcategory\x12'\n" +
	"\x0fdatasource_type\x18\x03 \x01(\tR\x0edatasourceType\"\x13\n" +
	"\x11GetSchemasRequest\"\x9b\x01\n" +
	"\x12GetSchemasResponse\x12I\n" +
	"\aschemas\x18\x01 \x03(\v2/.bino.plugin.v1.GetSchemasResponse.SchemasEntryR\aschemas\x1a:\n" +
	"\fSchemasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xe9\x01\n" +
	"\x18CollectDataSourceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\braw_spec\x18\x02 \x01(\fR\arawSpec\x12C\n" +
	"\x03env\x18\x03 \x03(\v21.bino.plugin.v1.CollectDataSourceRequest.EnvEntryR\x03env\x12!\n" +
	"\fproject_root\x18\x04 \x01(\tR\vprojectRoot\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe0\x02\n" +
	"\x19CollectDataSourceResponse\x12\x1b\n" +
	"\tjson_rows\x18\x01 \x01(\fR\bjsonRows\x12]\n" +
	"\fcolumn_types\x18\x02 \x03(\v2:.bino.plugin.v1.CollectDataSourceResponse.ColumnTypesEntryR\vcolumnTypes\x12\x1c\n" +
	"\tephemeral\x18\x03 \x01(\bR\tephemeral\x12<\n" +
	"\vdiagnostics\x18\x04 \x03(\v2\x1a.bino.plugin.v1.DiagnosticR\vdiagnostics\x12+\n" +
	"\x11duckdb_expression\x18\x05 \x01(\tR\x10duckdbExpression\x1a>\n" +
	"\x10ColumnTypesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd9\x01\n" +
	"\vLintRequest\x12:\n" +
	"\tdocuments\x18\x01 \x03(\v2\x1c.bino.plugin.v1.LintDocumentR\tdocuments\x12:\n" +
	"\bdatasets\x18\x02 \x03(\v2\x1e.bino.plugin.v1.DatasetPayloadR\bdatasets\x12-\n" +
	"\x12datasets_available\x18\x03 \x01(\bR\x11datasetsAvailable\x12#\n" +
	"\rrendered_html\x18\x04 \x01(\fR\frenderedHtml\"x\n" +
	"\fLintDocument\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x05R\bposition\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x10\n" +
	"\x03raw\x18\x05 \x01(\fR\x03raw\"G\n" +
	"\fLintResponse\x127\n" +
	"\bfindings\x18\x01 \x03(\v2\x1b.bino.plugin.v1.LintFindingR\bfindings\"\xe3\x01\n" +
	"\vLintFinding\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04file\x18\x03 \x01(\tR\x04file\x12\x17\n" +
	"\adoc_idx\x18\x04 \x01(\x05R\x06docIdx\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12\x12\n" +
	"\x04line\x18\x06 \x01(\x05R\x04line\x12\x16\n" +
	"\x06column\x18\a \x01(\x05R\x06column\x124\n" +
	"\bseverity\x18\b \x01(\x0e2\x18.bino.plugin.v1.SeverityR\bseverity\"3\n" +
	"\x10GetAssetsRequest\x12\x1f\n" +
	"\vrender_mode\x18\x01 \x01(\tR\n" +
	"renderMode\"{\n" +
	"\x11GetAssetsResponse\x123\n" +
	"\ascripts\x18\x01 \x03(\v2\x19.bino.plugin.v1.AssetFileR\ascripts\x121\n" +
	"\x06styles\x18\x02 \x03(\v2\x19.bino.plugin.v1.AssetFileR\x06styles\"\x99\x01\n" +
	"\tAssetFile\x12\x19\n" +
	"\burl_path\x18\x01 \x01(\tR\aurlPath\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12\x1d\n" +
	"\n" +
	"media_type\x18\x04 \x01(\tR\tmediaType\x12\x1b\n" +
	"\tis_module\x18\x05 \x01(\bR\bisModule\"\x9d\x01\n" +
	"\x11CommandDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05short\x18\x02 \x01(\tR\x05short\x12\x12\n" +
	"\x04long\x18\x03 \x01(\tR\x04long\x12\x14\n" +
	"\x05usage\x18\x04 \x01(\tR\x05usage\x124\n" +
	"\x05flags\x18\x05 \x03(\v2\x1e.bino.plugin.v1.FlagDescriptorR\x05flags\"\xb9\x01\n" +
	"\x0eFlagDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tshorthand\x18\x02 \x01(\tR\tshorthand\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rdefault_value\x18\x04 \x01(\tR\fdefaultValue\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x1a\n" +
	"\brequired\x18\x06 \x01(\bR\brequired\"\xdb\x01\n" +
	"\x12ExecCommandRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12C\n" +
	"\x05flags\x18\x03 \x03(\v2-.bino.plugin.v1.ExecCommandRequest.FlagsEntryR\x05flags\x12\x18\n" +
	"\aworkdir\x18\x04 \x01(\tR\aworkdir\x1a8\n" +
	"\n" +
	"FlagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"{\n" +
	"\x11ExecCommandOutput\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\fR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x19\n" +
	"\bis_final\x18\x04 \x01(\bR\aisFinal\"d\n" +
	"\vHookRequest\x12\x1e\n" +
	"\n" +
	"checkpoint\x18\x01 \x01(\tR\n" +
	"checkpoint\x125\n" +
	"\apayload\x18\x02 \x01(\v2\x1b.bino.plugin.v1.HookPayloadR\apayload\"\xbb\x02\n" +
	"\vHookPayload\x12=\n" +
	"\tdocuments\x18\x01 \x03(\v2\x1f.bino.plugin.v1.DocumentPayloadR\tdocuments\x12\x12\n" +
	"\x04html\x18\x02 \x01(\fR\x04html\x12\x19\n" +
	"\bpdf_path\x18\x03 \x01(\tR\apdfPath\x12:\n" +
	"\bdatasets\x18\x04 \x03(\v2\x1e.bino.plugin.v1.DatasetPayloadR\bdatasets\x12E\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2).bino.plugin.v1.HookPayload.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"{\n" +
	"\x0fDocumentPayload\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x05R\bposition\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x10\n" +
	"\x03raw\x18\x05 \x01(\fR\x03raw\"[\n" +
	"\x0eDatasetPayload\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tjson_rows\x18\x02 \x01(\fR\bjsonRows\x12\x18\n" +
	"\acolumns\x18\x03 \x03(\tR\acolumns\"\xd8\x01\n" +
	"\fHookResponse\x12\x1a\n" +
	"\bmodified\x18\x01 \x01(\bR\bmodified\x125\n" +
	"\apayload\x18\x02 \x01(\v2\x1b.bino.plugin.v1.HookPayloadR\apayload\x12<\n" +
	"\vdiagnostics\x18\x03 \x03(\v2\x1a.bino.plugin.v1.DiagnosticR\vdiagnostics\x127\n" +
	"\bfindings\x18\x04 \x03(\v2\x1b.bino.plugin.v1.LintFindingR\bfindings\"\x8a\x01\n" +
	"\n" +
	"Diagnostic\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x14\n" +
	"\x05stage\x18\x02 \x01(\tR\x05stage\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x124\n" +
	"\bseverity\x18\x04 \x01(\x0e2\x18.bino.plugin.v1.SeverityR\bseverity\"\x15\n" +
	"\x13ListCommandsRequest\"U\n" +
	"\x14ListCommandsResponse\x12=\n" +
	"\bcommands\x18\x01 \x03(\v2!.bino.plugin.v1.CommandDescriptorR\bcommands\"u\n" +
	"\x16RenderComponentRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04spec\x18\x03 \x01(\fR\x04spec\x12\x1f\n" +
	"\vrender_mode\x18\x04 \x01(\tR\n" +
	"renderMode\"k\n" +
	"\x17RenderComponentResponse\x12\x12\n" +
	"\x04html\x18\x01 \x01(\tR\x04html\x12<\n" +
	"\vdiagnostics\x18\x02 \x03(\v2\x1a.bino.plugin.v1.DiagnosticR\vdiagnostics\" \n" +
	"\fQueryRequest\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\"\x84\x01\n" +
	"\rQueryResponse\x12\x1b\n" +
	"\tjson_rows\x18\x01 \x01(\fR\bjsonRows\x12\x18\n" +
	"\acolumns\x18\x02 \x03(\tR\acolumns\x12<\n" +
	"\vdiagnostics\x18\x03 \x03(\v2\x1a.bino.plugin.v1.DiagnosticR\vdiagnostics\"<\n" +
	"\x12GetDocumentRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"h\n" +
	"\x13GetDocumentResponse\x12;\n" +
	"\bdocument\x18\x01 \x01(\v2\x1f.bino.plugin.v1.DocumentPayloadR\bdocument\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"-\n" +
	"\x17GetDatasetResultRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"j\n" +
	"\x18GetDatasetResultResponse\x128\n" +
	"\adataset\x18\x01 \x01(\v2\x1e.bino.plugin.v1.DatasetPayloadR\adataset\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"7\n" +
	"\x14ListDocumentsRequest\x12\x1f\n" +
	"\vkind_filter\x18\x01 \x01(\tR\n" +
	"kindFilter\"V\n" +
	"\x15ListDocumentsResponse\x12=\n" +
	"\tdocuments\x18\x01 \x03(\v2\x1f.bino.plugin.v1.DocumentPayloadR\tdocuments*[\n" +
	"\fKindCategory\x12\x13\n" +
	"\x0fKIND_DATASOURCE\x10\x00\x12\x12\n" +
	"\x0eKIND_COMPONENT\x10\x01\x12\x0f\n" +
	"\vKIND_CONFIG\x10\x02\x12\x11\n" +
	"\rKIND_ARTIFACT\x10\x03*,\n" +
	"\bSeverity\x12\v\n" +
	"\aWARNING\x10\x00\x12\t\n" +
	"\x05ERROR\x10\x01\x12\b\n" +
	"\x04INFO\x10\x022\xd0\x06\n" +
	"\n" +
	"BinoPlugin\x12C\n" +
	"\x04Init\x12\x1b.bino.plugin.v1.InitRequest\x1a\x1e.bino.plugin.v1.PluginManifest\x12M\n" +
	"\bShutdown\x12\x1f.bino.plugin.v1.ShutdownRequest\x1a .bino.plugin.v1.ShutdownResponse\x12S\n" +
	"\n" +
	"GetSchemas\x12!.bino.plugin.v1.GetSchemasRequest\x1a\".bino.plugin.v1.GetSchemasResponse\x12h\n" +
	"\x11CollectDataSource\x12(.bino.plugin.v1.CollectDataSourceRequest\x1a).bino.plugin.v1.CollectDataSourceResponse\x12A\n" +
	"\x04Lint\x12\x1b.bino.plugin.v1.LintRequest\x1a\x1c.bino.plugin.v1.LintResponse\x12P\n" +
	"\tGetAssets\x12 .bino.plugin.v1.GetAssetsRequest\x1a!.bino.plugin.v1.GetAssetsResponse\x12Y\n" +
	"\fListCommands\x12#.bino.plugin.v1.ListCommandsRequest\x1a$.bino.plugin.v1.ListCommandsResponse\x12V\n" +
	"\vExecCommand\x12\".bino.plugin.v1.ExecCommandRequest\x1a!.bino.plugin.v1.ExecCommandOutput0\x01\x12C\n" +
	"\x06OnHook\x12\x1b.bino.plugin.v1.HookRequest\x1a\x1c.bino.plugin.v1.HookResponse\x12b\n" +
	"\x0fRenderComponent\x12&.bino.plugin.v1.RenderComponentRequest\x1a'.bino.plugin.v1.RenderComponentResponse2\xf3\x02\n" +
	"\bBinoHost\x12J\n" +
	"\vQueryDuckDB\x12\x1c.bino.plugin.v1.QueryRequest\x1a\x1d.bino.plugin.v1.QueryResponse\x12V\n" +
	"\vGetDocument\x12\".bino.plugin.v1.GetDocumentRequest\x1a#.bino.plugin.v1.GetDocumentResponse\x12e\n" +
	"\x10GetDatasetResult\x12'.bino.plugin.v1.GetDatasetResultRequest\x1a(.bino.plugin.v1.GetDatasetResultResponse\x12\\\n" +
	"\rListDocuments\x12$.bino.plugin.v1.ListDocumentsRequest\x1a%.bino.plugin.v1.ListDocumentsResponseB6Z4github.com/bino-bi/bino-plugin-sdk/proto/v1;pluginv1b\x06proto3"

var (
	file_proto_v1_plugin_proto_rawDescOnce sync.Once
	file_proto_v1_plugin_proto_rawDescData []byte
)

func file_proto_v1_plugin_proto_rawDescGZIP() []byte {
	file_proto_v1_plugin_proto_rawDescOnce.Do(func() {
		file_proto_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_plugin_proto_rawDesc), len(file_proto_v1_plugin_proto_rawDesc)))
	})
	return file_proto_v1_plugin_proto_rawDescData
}

var file_proto_v1_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 44)
var file_proto_v1_plugin_proto_goTypes = []any{
	(KindCategory)(0),                 // 0: bino.plugin.v1.KindCategory
	(Severity)(0),                     // 1: bino.plugin.v1.Severity
	(*InitRequest)(nil),               // 2: bino.plugin.v1.InitRequest
	(*PluginManifest)(nil),            // 3: bino.plugin.v1.PluginManifest
	(*ShutdownRequest)(nil),           // 4: bino.plugin.v1.ShutdownRequest
	(*ShutdownResponse)(nil),          // 5: bino.plugin.v1.ShutdownResponse
	(*KindRegistration)(nil),          // 6: bino.plugin.v1.KindRegistration
	(*GetSchemasRequest)(nil),         // 7: bino.plugin.v1.GetSchemasRequest
	(*GetSchemasResponse)(nil),        // 8: bino.plugin.v1.GetSchemasResponse
	(*CollectDataSourceRequest)(nil),  // 9: bino.plugin.v1.CollectDataSourceRequest
	(*CollectDataSourceResponse)(nil), // 10: bino.plugin.v1.CollectDataSourceResponse
	(*LintRequest)(nil),               // 11: bino.plugin.v1.LintRequest
	(*LintDocument)(nil),              // 12: bino.plugin.v1.LintDocument
	(*LintResponse)(nil),              // 13: bino.plugin.v1.LintResponse
	(*LintFinding)(nil),               // 14: bino.plugin.v1.LintFinding
	(*GetAssetsRequest)(nil),          // 15: bino.plugin.v1.GetAssetsRequest
	(*GetAssetsResponse)(nil),         // 16: bino.plugin.v1.GetAssetsResponse
	(*AssetFile)(nil),                 // 17: bino.plugin.v1.AssetFile
	(*CommandDescriptor)(nil),         // 18: bino.plugin.v1.CommandDescriptor
	(*FlagDescriptor)(nil),            // 19: bino.plugin.v1.FlagDescriptor
	(*ExecCommandRequest)(nil),        // 20: bino.plugin.v1.ExecCommandRequest
	(*ExecCommandOutput)(nil),         // 21: bino.plugin.v1.ExecCommandOutput
	(*HookRequest)(nil),               // 22: bino.plugin.v1.HookRequest
	(*HookPayload)(nil),               // 23: bino.plugin.v1.HookPayload
	(*DocumentPayload)(nil),           // 24: bino.plugin.v1.DocumentPayload
	(*DatasetPayload)(nil),            // 25: bino.plugin.v1.DatasetPayload
	(*HookResponse)(nil),              // 26: bino.plugin.v1.HookResponse
	(*Diagnostic)(nil),                // 27: bino.plugin.v1.Diagnostic
	(*ListCommandsRequest)(nil),       // 28: bino.plugin.v1.ListCommandsRequest
	(*ListCommandsResponse)(nil),      // 29: bino.plugin.v1.ListCommandsResponse
	(*RenderComponentRequest)(nil),    // 30: bino.plugin.v1.RenderComponentRequest
	(*RenderComponentResponse)(nil),   // 31: bino.plugin.v1.RenderComponentResponse
	(*QueryRequest)(nil),              // 32: bino.plugin.v1.QueryRequest
	(*QueryResponse)(nil),             // 33: bino.plugin.v1.QueryResponse
	(*GetDocumentRequest)(nil),        // 34: bino.plugin.v1.GetDocumentRequest
	(*GetDocumentResponse)(nil),       // 35: bino.plugin.v1.GetDocumentResponse
	(*GetDatasetResultRequest)(nil),   // 36: bino.plugin.v1.GetDatasetResultRequest
	(*GetDatasetResultResponse)(nil),  // 37: bino.plugin.v1.GetDatasetResultResponse
	(*ListDocumentsRequest)(nil),      // 38: bino.plugin.v1.ListDocumentsRequest
	(*ListDocumentsResponse)(nil),     // 39: bino.plugin.v1.ListDocumentsResponse
	nil,                               // 40: bino.plugin.v1.InitRequest.ConfigEntry
	nil,                               // 41: bino.plugin.v1.GetSchemasResponse.SchemasEntry
	nil,                               // 42: bino.plugin.v1.CollectDataSourceRequest.EnvEntry
	nil,                               // 43: bino.plugin.v1.CollectDataSourceResponse.ColumnTypesEntry
	nil,                               // 44: bino.plugin.v1.ExecCommandRequest.FlagsEntry
	nil,                               // 45: bino.plugin.v1.HookPayload.MetadataEntry
}
var file_proto_v1_plugin_proto_depIdxs = []int32{
	40, // 0: bino.plugin.v1.InitRequest.config:type_name -> bino.plugin.v1.InitRequest.ConfigEntry
	6,  // 1: bino.plugin.v1.PluginManifest.kinds:type_name -> bino.plugin.v1.KindRegistration
	18, // 2: bino.plugin.v1.PluginManifest.commands:type_name -> bino.plugin.v1.CommandDescriptor
	0,  // 3: bino.plugin.v1.KindRegistration.category:type_name -> bino.plugin.v1.KindCategory
	41, // 4: bino.plugin.v1.GetSchemasResponse.schemas:type_name -> bino.plugin.v1.GetSchemasResponse.SchemasEntry
	42, // 5: bino.plugin.v1.CollectDataSourceRequest.env:type_name -> bino.plugin.v1.CollectDataSourceRequest.EnvEntry
	43, // 6: bino.plugin.v1.CollectDataSourceResponse.column_types:type_name -> bino.plugin.v1.CollectDataSourceResponse.ColumnTypesEntry
	27, // 7: bino.plugin.v1.CollectDataSourceResponse.diagnostics:type_name -> bino.plugin.v1.Diagnostic
	12, // 8: bino.plugin.v1.LintRequest.documents:type_name -> bino.plugin.v1.LintDocument
	25, // 9: bino.plugin.v1.LintRequest.datasets:type_name -> bino.plugin.v1.DatasetPayload
	14, // 10: bino.plugin.v1.LintResponse.findings:type_name -> bino.plugin.v1.LintFinding
	1,  // 11: bino.plugin.v1.LintFinding.severity:type_name -> bino.plugin.v1.Severity
	17, // 12: bino.plugin.v1.GetAssetsResponse.scripts:type_name -> bino.plugin.v1.AssetFile
	17, // 13: bino.plugin.v1.GetAssetsResponse.styles:type_name -> bino.plugin.v1.AssetFile
	19, // 14: bino.plugin.v1.CommandDescriptor.flags:type_name -> bino.plugin.v1.FlagDescriptor
	44, // 15: bino.plugin.v1.ExecCommandRequest.flags:type_name -> bino.plugin.v1.ExecCommandRequest.FlagsEntry
	23, // 16: bino.plugin.v1.HookRequest.payload:type_name -> bino.plugin.v1.HookPayload
	24, // 17: bino.plugin.v1.HookPayload.documents:type_name -> bino.plugin.v1.DocumentPayload
	25, // 18: bino.plugin.v1.HookPayload.datasets:type_name -> bino.plugin.v1.DatasetPayload
	45, // 19: bino.plugin.v1.HookPayload.metadata:type_name -> bino.plugin.v1.HookPayload.MetadataEntry
	23, // 20: bino.plugin.v1.HookResponse.payload:type_name -> bino.plugin.v1.HookPayload
	27, // 21: bino.plugin.v1.HookResponse.diagnostics:type_name -> bino.plugin.v1.Diagnostic
	14, // 22: bino.plugin.v1.HookResponse.findings:type_name -> bino.plugin.v1.LintFinding
	1,  // 23: bino.plugin.v1.Diagnostic.severity:type_name -> bino.plugin.v1.Severity
	18, // 24: bino.plugin.v1.ListCommandsResponse.commands:type_name -> bino.plugin.v1.CommandDescriptor
	27, // 25: bino.plugin.v1.RenderComponentResponse.diagnostics:type_name -> bino.plugin.v1.Diagnostic
	27, // 26: bino.plugin.v1.QueryResponse.diagnostics:type_name -> bino.plugin.v1.Diagnostic
	24, // 27: bino.plugin.v1.GetDocumentResponse.document:type_name -> bino.plugin.v1.DocumentPayload
	25, // 28: bino.plugin.v1.GetDatasetResultResponse.dataset:type_name -> bino.plugin.v1.DatasetPayload
	24, // 29: bino.plugin.v1.ListDocumentsResponse.documents:type_name -> bino.plugin.v1.DocumentPayload
	2,  // 30: bino.plugin.v1.BinoPlugin.Init:input_type -> bino.plugin.v1.InitRequest
	4,  // 31: bino.plugin.v1.BinoPlugin.Shutdown:input_type -> bino.plugin.v1.ShutdownRequest
	7,  // 32: bino.plugin.v1.BinoPlugin.GetSchemas:input_type -> bino.plugin.v1.GetSchemasRequest
	9,  // 33: bino.plugin.v1.BinoPlugin.CollectDataSource:input_type -> bino.plugin.v1.CollectDataSourceRequest
	11, // 34: bino.plugin.v1.BinoPlugin.Lint:input_type -> bino.plugin.v1.LintRequest
	15, // 35: bino.plugin.v1.BinoPlugin.GetAssets:input_type -> bino.plugin.v1.GetAssetsRequest
	28, // 36: bino.plugin.v1.BinoPlugin.ListCommands:input_type -> bino.plugin.v1.ListCommandsRequest
	20, // 37: bino.plugin.v1.BinoPlugin.ExecCommand:input_type -> bino.plugin.v1.ExecCommandRequest
	22, // 38: bino.plugin.v1.BinoPlugin.OnHook:input_type -> bino.plugin.v1.HookRequest
	30, // 39: bino.plugin.v1.BinoPlugin.RenderComponent:input_type -> bino.plugin.v1.RenderComponentRequest
	32, // 40: bino.plugin.v1.BinoHost.QueryDuckDB:input_type -> bino.plugin.v1.QueryRequest
	34, // 41: bino.plugin.v1.BinoHost.GetDocument:input_type -> bino.plugin.v1.GetDocumentRequest
	36, // 42: bino.plugin.v1.BinoHost.GetDatasetResult:input_type -> bino.plugin.v1.GetDatasetResultRequest
	38, // 43: bino.plugin.v1.BinoHost.ListDocuments:input_type -> bino.plugin.v1.ListDocumentsRequest
	3,  // 44: bino.plugin.v1.BinoPlugin.Init:output_type -> bino.plugin.v1.PluginManifest
	5,  // 45: bino.plugin.v1.BinoPlugin.Shutdown:output_type -> bino.plugin.v1.ShutdownResponse
	8,  // 46: bino.plugin.v1.BinoPlugin.GetSchemas:output_type -> bino.plugin.v1.GetSchemasResponse
	10, // 47: bino.plugin.v1.BinoPlugin.CollectDataSource:output_type -> bino.plugin.v1.CollectDataSourceResponse
	13, // 48: bino.plugin.v1.BinoPlugin.Lint:output_type -> bino.plugin.v1.LintResponse
	16, // 49: bino.plugin.v1.BinoPlugin.GetAssets:output_type -> bino.plugin.v1.GetAssetsResponse
	29, // 50: bino.plugin.v1.BinoPlugin.ListCommands:output_type -> bino.plugin.v1.ListCommandsResponse
	21, // 51: bino.plugin.v1.BinoPlugin.ExecCommand:output_type -> bino.plugin.v1.ExecCommandOutput
	26, // 52: bino.plugin.v1.BinoPlugin.OnHook:output_type -> bino.plugin.v1.HookResponse
	31, // 53: bino.plugin.v1.BinoPlugin.RenderComponent:output_type -> bino.plugin.v1.RenderComponentResponse
	33, // 54: bino.plugin.v1.BinoHost.QueryDuckDB:output_type -> bino.plugin.v1.QueryResponse
	35, // 55: bino.plugin.v1.BinoHost.GetDocument:output_type -> bino.plugin.v1.GetDocumentResponse
	37, // 56: bino.plugin.v1.BinoHost.GetDatasetResult:output_type -> bino.plugin.v1.GetDatasetResultResponse
	39, // 57: bino.plugin.v1.BinoHost.ListDocuments:output_type -> bino.plugin.v1.ListDocumentsResponse
	44, // [44:58] is the sub-list for method output_type
	30, // [30:44] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_proto_v1_plugin_proto_init() }
func file_proto_v1_plugin_proto_init() {
	if File_proto_v1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_plugin_proto_rawDesc), len(file_proto_v1_plugin_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   44,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_v1_plugin_proto_goTypes,
		DependencyIndexes: file_proto_v1_plugin_proto_depIdxs,
		EnumInfos:         file_proto_v1_plugin_proto_enumTypes,
		MessageInfos:      file_proto_v1_plugin_proto_msgTypes,
	}.Build()
	File_proto_v1_plugin_proto = out.File
	file_proto_v1_plugin_proto_goTypes = nil
	file_proto_v1_plugin_proto_depIdxs = nil
}
