// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/v1/plugin.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BinoPlugin_Init_FullMethodName              = "/bino.plugin.v1.BinoPlugin/Init"
	BinoPlugin_Shutdown_FullMethodName          = "/bino.plugin.v1.BinoPlugin/Shutdown"
	BinoPlugin_GetSchemas_FullMethodName        = "/bino.plugin.v1.BinoPlugin/GetSchemas"
	BinoPlugin_CollectDataSource_FullMethodName = "/bino.plugin.v1.BinoPlugin/CollectDataSource"
	BinoPlugin_Lint_FullMethodName              = "/bino.plugin.v1.BinoPlugin/Lint"
	BinoPlugin_GetAssets_FullMethodName         = "/bino.plugin.v1.BinoPlugin/GetAssets"
	BinoPlugin_ListCommands_FullMethodName      = "/bino.plugin.v1.BinoPlugin/ListCommands"
	BinoPlugin_ExecCommand_FullMethodName       = "/bino.plugin.v1.BinoPlugin/ExecCommand"
	BinoPlugin_OnHook_FullMethodName            = "/bino.plugin.v1.BinoPlugin/OnHook"
	BinoPlugin_RenderComponent_FullMethodName   = "/bino.plugin.v1.BinoPlugin/RenderComponent"
)

// BinoPluginClient is the client API for BinoPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BinoPlugin is the main service that every plugin must implement.
type BinoPluginClient interface {
	// Init is called once after connection. The plugin receives its
	// configuration and returns a manifest describing its capabilities.
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*PluginManifest, error)
	// Shutdown is called before the host terminates the plugin process.
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
	// GetSchemas returns JSON Schema definitions for all kinds this
	// plugin provides. Called once at startup and cached.
	GetSchemas(ctx context.Context, in *GetSchemasRequest, opts ...grpc.CallOption) (*GetSchemasResponse, error)
	// CollectDataSource processes a custom DataSource document and
	// returns tabular data (JSON rows) to be registered as a DuckDB view.
	CollectDataSource(ctx context.Context, in *CollectDataSourceRequest, opts ...grpc.CallOption) (*CollectDataSourceResponse, error)
	// Lint receives all loaded documents and returns findings.
	Lint(ctx context.Context, in *LintRequest, opts ...grpc.CallOption) (*LintResponse, error)
	// GetAssets returns JS/CSS assets to inject into rendered HTML.
	GetAssets(ctx context.Context, in *GetAssetsRequest, opts ...grpc.CallOption) (*GetAssetsResponse, error)
	// ListCommands returns subcommand descriptors for bino help.
	ListCommands(ctx context.Context, in *ListCommandsRequest, opts ...grpc.CallOption) (*ListCommandsResponse, error)
	// ExecCommand executes a plugin-provided CLI subcommand.
	ExecCommand(ctx context.Context, in *ExecCommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecCommandOutput], error)
	// OnHook is called at each pipeline checkpoint. The plugin can
	// inspect and optionally modify the payload.
	OnHook(ctx context.Context, in *HookRequest, opts ...grpc.CallOption) (*HookResponse, error)
	// RenderComponent generates HTML for a plugin-provided component kind.
	// Called once per component instance during layout rendering.
	RenderComponent(ctx context.Context, in *RenderComponentRequest, opts ...grpc.CallOption) (*RenderComponentResponse, error)
}

type binoPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewBinoPluginClient(cc grpc.ClientConnInterface) BinoPluginClient {
	return &binoPluginClient{cc}
}

func (c *binoPluginClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*PluginManifest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginManifest)
	err := c.cc.Invoke(ctx, BinoPlugin_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *binoPluginClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, BinoPlugin_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *binoPluginClient) GetSchemas(ctx context.Context, in *GetSchemasRequest, opts ...grpc.CallOption) (*GetSchemasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSchemasResponse)
	err := c.cc.Invoke(ctx, BinoPlugin_GetSchemas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *binoPluginClient) CollectDataSource(ctx context.Context, in *CollectDataSourceRequest, opts ...grpc.CallOption) (*CollectDataSourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectDataSourceResponse)
	err := c.cc.Invoke(ctx, BinoPlugin_CollectDataSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *binoPluginClient) Lint(ctx context.Context, in *LintRequest, opts ...grpc.CallOption) (*LintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LintResponse)
	err := c.cc.Invoke(ctx, BinoPlugin_Lint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *binoPluginClient) GetAssets(ctx context.Context, in *GetAssetsRequest, opts ...grpc.CallOption) (*GetAssetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAssetsResponse)
	err := c.cc.Invoke(ctx, BinoPlugin_GetAssets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *binoPluginClient) ListCommands(ctx context.Context, in *ListCommandsRequest, opts ...grpc.CallOption) (*ListCommandsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCommandsResponse)
	err := c.cc.Invoke(ctx, BinoPlugin_ListCommands_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *binoPluginClient) ExecCommand(ctx context.Context, in *ExecCommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecCommandOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BinoPlugin_ServiceDesc.Streams[0], BinoPlugin_ExecCommand_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecCommandRequest, ExecCommandOutput]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BinoPlugin_ExecCommandClient = grpc.ServerStreamingClient[ExecCommandOutput]

func (c *binoPluginClient) OnHook(ctx context.Context, in *HookRequest, opts ...grpc.CallOption) (*HookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HookResponse)
	err := c.cc.Invoke(ctx, BinoPlugin_OnHook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *binoPluginClient) RenderComponent(ctx context.Context, in *RenderComponentRequest, opts ...grpc.CallOption) (*RenderComponentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenderComponentResponse)
	err := c.cc.Invoke(ctx, BinoPlugin_RenderComponent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BinoPluginServer is the server API for BinoPlugin service.
// All implementations must embed UnimplementedBinoPluginServer
// for forward compatibility.
//
// BinoPlugin is the main service that every plugin must implement.
type BinoPluginServer interface {
	// Init is called once after connection. The plugin receives its
	// configuration and returns a manifest describing its capabilities.
	Init(context.Context, *InitRequest) (*PluginManifest, error)
	// Shutdown is called before the host terminates the plugin process.
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	// GetSchemas returns JSON Schema definitions for all kinds this
	// plugin provides. Called once at startup and cached.
	GetSchemas(context.Context, *GetSchemasRequest) (*GetSchemasResponse, error)
	// CollectDataSource processes a custom DataSource document and
	// returns tabular data (JSON rows) to be registered as a DuckDB view.
	CollectDataSource(context.Context, *CollectDataSourceRequest) (*CollectDataSourceResponse, error)
	// Lint receives all loaded documents and returns findings.
	Lint(context.Context, *LintRequest) (*LintResponse, error)
	// GetAssets returns JS/CSS assets to inject into rendered HTML.
	GetAssets(context.Context, *GetAssetsRequest) (*GetAssetsResponse, error)
	// ListCommands returns subcommand descriptors for bino help.
	ListCommands(context.Context, *ListCommandsRequest) (*ListCommandsResponse, error)
	// ExecCommand executes a plugin-provided CLI subcommand.
	ExecCommand(*ExecCommandRequest, grpc.ServerStreamingServer[ExecCommandOutput]) error
	// OnHook is called at each pipeline checkpoint. The plugin can
	// inspect and optionally modify the payload.
	OnHook(context.Context, *HookRequest) (*HookResponse, error)
	// RenderComponent generates HTML for a plugin-provided component kind.
	// Called once per component instance during layout rendering.
	RenderComponent(context.Context, *RenderComponentRequest) (*RenderComponentResponse, error)
	mustEmbedUnimplementedBinoPluginServer()
}

// UnimplementedBinoPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBinoPluginServer struct{}

func (UnimplementedBinoPluginServer) Init(context.Context, *InitRequest) (*PluginManifest, error) {
	return nil, status.Error(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedBinoPluginServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedBinoPluginServer) GetSchemas(context.Context, *GetSchemasRequest) (*GetSchemasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSchemas not implemented")
}
func (UnimplementedBinoPluginServer) CollectDataSource(context.Context, *CollectDataSourceRequest) (*CollectDataSourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectDataSource not implemented")
}
func (UnimplementedBinoPluginServer) Lint(context.Context, *LintRequest) (*LintResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Lint not implemented")
}
func (UnimplementedBinoPluginServer) GetAssets(context.Context, *GetAssetsRequest) (*GetAssetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAssets not implemented")
}
func (UnimplementedBinoPluginServer) ListCommands(context.Context, *ListCommandsRequest) (*ListCommandsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCommands not implemented")
}
func (UnimplementedBinoPluginServer) ExecCommand(*ExecCommandRequest, grpc.ServerStreamingServer[ExecCommandOutput]) error {
	return status.Error(codes.Unimplemented, "method ExecCommand not implemented")
}
func (UnimplementedBinoPluginServer) OnHook(context.Context, *HookRequest) (*HookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OnHook not implemented")
}
func (UnimplementedBinoPluginServer) RenderComponent(context.Context, *RenderComponentRequest) (*RenderComponentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenderComponent not implemented")
}
func (UnimplementedBinoPluginServer) mustEmbedUnimplementedBinoPluginServer() {}
func (UnimplementedBinoPluginServer) testEmbeddedByValue()                    {}

// UnsafeBinoPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BinoPluginServer will
// result in compilation errors.
type UnsafeBinoPluginServer interface {
	mustEmbedUnimplementedBinoPluginServer()
}

func RegisterBinoPluginServer(s grpc.ServiceRegistrar, srv BinoPluginServer) {
	// If the following call panics, it indicates UnimplementedBinoPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BinoPlugin_ServiceDesc, srv)
}

func _BinoPlugin_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BinoPluginServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BinoPlugin_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BinoPluginServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BinoPlugin_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BinoPluginServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BinoPlugin_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BinoPluginServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BinoPlugin_GetSchemas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSchemasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BinoPluginServer).GetSchemas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BinoPlugin_GetSchemas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BinoPluginServer).GetSchemas(ctx, req.(*GetSchemasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BinoPlugin_CollectDataSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectDataSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BinoPluginServer).CollectDataSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BinoPlugin_CollectDataSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BinoPluginServer).CollectDataSource(ctx, req.(*CollectDataSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BinoPlugin_Lint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BinoPluginServer).Lint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BinoPlugin_Lint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BinoPluginServer).Lint(ctx, req.(*LintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BinoPlugin_GetAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BinoPluginServer).GetAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BinoPlugin_GetAssets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BinoPluginServer).GetAssets(ctx, req.(*GetAssetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BinoPlugin_ListCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BinoPluginServer).ListCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BinoPlugin_ListCommands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BinoPluginServer).ListCommands(ctx, req.(*ListCommandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BinoPlugin_ExecCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecCommandRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BinoPluginServer).ExecCommand(m, &grpc.GenericServerStream[ExecCommandRequest, ExecCommandOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BinoPlugin_ExecCommandServer = grpc.ServerStreamingServer[ExecCommandOutput]

func _BinoPlugin_OnHook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BinoPluginServer).OnHook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BinoPlugin_OnHook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BinoPluginServer).OnHook(ctx, req.(*HookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BinoPlugin_RenderComponent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderComponentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BinoPluginServer).RenderComponent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BinoPlugin_RenderComponent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BinoPluginServer).RenderComponent(ctx, req.(*RenderComponentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BinoPlugin_ServiceDesc is the grpc.ServiceDesc for BinoPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BinoPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bino.plugin.v1.BinoPlugin",
	HandlerType: (*BinoPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _BinoPlugin_Init_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _BinoPlugin_Shutdown_Handler,
		},
		{
			MethodName: "GetSchemas",
			Handler:    _BinoPlugin_GetSchemas_Handler,
		},
		{
			MethodName: "CollectDataSource",
			Handler:    _BinoPlugin_CollectDataSource_Handler,
		},
		{
			MethodName: "Lint",
			Handler:    _BinoPlugin_Lint_Handler,
		},
		{
			MethodName: "GetAssets",
			Handler:    _BinoPlugin_GetAssets_Handler,
		},
		{
			MethodName: "ListCommands",
			Handler:    _BinoPlugin_ListCommands_Handler,
		},
		{
			MethodName: "OnHook",
			Handler:    _BinoPlugin_OnHook_Handler,
		},
		{
			MethodName: "RenderComponent",
			Handler:    _BinoPlugin_RenderComponent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecCommand",
			Handler:       _BinoPlugin_ExecCommand_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/v1/plugin.proto",
}

const (
	BinoHost_QueryDuckDB_FullMethodName      = "/bino.plugin.v1.BinoHost/QueryDuckDB"
	BinoHost_GetDocument_FullMethodName      = "/bino.plugin.v1.BinoHost/GetDocument"
	BinoHost_GetDatasetResult_FullMethodName = "/bino.plugin.v1.BinoHost/GetDatasetResult"
	BinoHost_ListDocuments_FullMethodName    = "/bino.plugin.v1.BinoHost/ListDocuments"
)

// BinoHostClient is the client API for BinoHost service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BinoHost is a service exposed by the CLI host via go-plugin's GRPCBroker.
// Plugins receive the broker service ID in InitRequest.host_service_id and
// dial back to query host state (DuckDB, documents, datasets).
type BinoHostClient interface {
	// QueryDuckDB executes a SQL query against the host's DuckDB engine.
	QueryDuckDB(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// GetDocument returns a single manifest document by kind and name.
	GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error)
	// GetDatasetResult returns pre-executed dataset results by name.
	GetDatasetResult(ctx context.Context, in *GetDatasetResultRequest, opts ...grpc.CallOption) (*GetDatasetResultResponse, error)
	// ListDocuments returns all loaded documents, optionally filtered by kind.
	ListDocuments(ctx context.Context, in *ListDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsResponse, error)
}

type binoHostClient struct {
	cc grpc.ClientConnInterface
}

func NewBinoHostClient(cc grpc.ClientConnInterface) BinoHostClient {
	return &binoHostClient{cc}
}

func (c *binoHostClient) QueryDuckDB(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, BinoHost_QueryDuckDB_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *binoHostClient) GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDocumentResponse)
	err := c.cc.Invoke(ctx, BinoHost_GetDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *binoHostClient) GetDatasetResult(ctx context.Context, in *GetDatasetResultRequest, opts ...grpc.CallOption) (*GetDatasetResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDatasetResultResponse)
	err := c.cc.Invoke(ctx, BinoHost_GetDatasetResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *binoHostClient) ListDocuments(ctx context.Context, in *ListDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDocumentsResponse)
	err := c.cc.Invoke(ctx, BinoHost_ListDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BinoHostServer is the server API for BinoHost service.
// All implementations must embed UnimplementedBinoHostServer
// for forward compatibility.
//
// BinoHost is a service exposed by the CLI host via go-plugin's GRPCBroker.
// Plugins receive the broker service ID in InitRequest.host_service_id and
// dial back to query host state (DuckDB, documents, datasets).
type BinoHostServer interface {
	// QueryDuckDB executes a SQL query against the host's DuckDB engine.
	QueryDuckDB(context.Context, *QueryRequest) (*QueryResponse, error)
	// GetDocument returns a single manifest document by kind and name.
	GetDocument(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error)
	// GetDatasetResult returns pre-executed dataset results by name.
	GetDatasetResult(context.Context, *GetDatasetResultRequest) (*GetDatasetResultResponse, error)
	// ListDocuments returns all loaded documents, optionally filtered by kind.
	ListDocuments(context.Context, *ListDocumentsRequest) (*ListDocumentsResponse, error)
	mustEmbedUnimplementedBinoHostServer()
}

// UnimplementedBinoHostServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBinoHostServer struct{}

func (UnimplementedBinoHostServer) QueryDuckDB(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryDuckDB not implemented")
}
func (UnimplementedBinoHostServer) GetDocument(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDocument not implemented")
}
func (UnimplementedBinoHostServer) GetDatasetResult(context.Context, *GetDatasetResultRequest) (*GetDatasetResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDatasetResult not implemented")
}
func (UnimplementedBinoHostServer) ListDocuments(context.Context, *ListDocumentsRequest) (*ListDocumentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDocuments not implemented")
}
func (UnimplementedBinoHostServer) mustEmbedUnimplementedBinoHostServer() {}
func (UnimplementedBinoHostServer) testEmbeddedByValue()                  {}

// UnsafeBinoHostServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BinoHostServer will
// result in compilation errors.
type UnsafeBinoHostServer interface {
	mustEmbedUnimplementedBinoHostServer()
}

func RegisterBinoHostServer(s grpc.ServiceRegistrar, srv BinoHostServer) {
	// If the following call panics, it indicates UnimplementedBinoHostServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BinoHost_ServiceDesc, srv)
}

func _BinoHost_QueryDuckDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BinoHostServer).QueryDuckDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BinoHost_QueryDuckDB_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BinoHostServer).QueryDuckDB(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BinoHost_GetDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BinoHostServer).GetDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BinoHost_GetDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BinoHostServer).GetDocument(ctx, req.(*GetDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BinoHost_GetDatasetResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDatasetResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BinoHostServer).GetDatasetResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BinoHost_GetDatasetResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BinoHostServer).GetDatasetResult(ctx, req.(*GetDatasetResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BinoHost_ListDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BinoHostServer).ListDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BinoHost_ListDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BinoHostServer).ListDocuments(ctx, req.(*ListDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BinoHost_ServiceDesc is the grpc.ServiceDesc for BinoHost service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BinoHost_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bino.plugin.v1.BinoHost",
	HandlerType: (*BinoHostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryDuckDB",
			Handler:    _BinoHost_QueryDuckDB_Handler,
		},
		{
			MethodName: "GetDocument",
			Handler:    _BinoHost_GetDocument_Handler,
		},
		{
			MethodName: "GetDatasetResult",
			Handler:    _BinoHost_GetDatasetResult_Handler,
		},
		{
			MethodName: "ListDocuments",
			Handler:    _BinoHost_ListDocuments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/plugin.proto",
}
